name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish AsxDbScraper/AsxDbScraper.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: ./publish

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: ./publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Assign Storage Blob Data Contributor Role
        run: |
          # Get storage account name from function app settings
          STORAGE_ACCOUNT=$(az functionapp show \
            --name asx-db-scraper-${{ github.event.inputs.environment || 'dev' }} \
            --resource-group asx-db-rg \
            --query "siteConfig.appSettings[?name=='AzureWebJobsStorage'].value" \
            --output tsv | cut -d';' -f3 | cut -d'=' -f2)
          
          # Get service principal object ID
          SP_OBJECT_ID=$(az ad sp list --display-name "asx-db-scraper-github" --query "[0].id" -o tsv)
          
          # Assign Storage Blob Data Contributor role
          az role assignment create \
            --assignee-object-id $SP_OBJECT_ID \
            --assignee-principal-type ServicePrincipal \
            --role "Storage Blob Data Contributor" \
            --scope "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/asx-db-rg/providers/Microsoft.Storage/storageAccounts/$STORAGE_ACCOUNT"

      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: asx-db-scraper-${{ github.event.inputs.environment || 'dev' }}
          package: ./publish 