name: Test Azure Credentials

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test Resource Group Access
        run: |
          echo "Testing access to resource group..."
          az group show --name asx-db-rg
          
          echo "Listing resources in the resource group..."
          az resource list --resource-group asx-db-rg --query "[].{name:name, type:type}" -o table
          
          echo "Testing Cosmos DB access..."
          az cosmosdb show --name asx-db-scraper-dev --resource-group asx-db--rg
          
          echo "Testing Function App access..."
          az functionapp show --name asx-db-scraper-dev --resource-group asx-db-rg
          
          echo "Testing Key Vault access..."
          az keyvault show --name asx-db-scraper-dev-kv --resource-group asx-db-rg

      - name: Test Storage Account Access
        run: |
          echo "Testing Storage Account access..."
          az storage account show --name asx-db-scraperdev --resource-group asx-db-rg
          
          echo "Listing storage account keys..."
          az storage account keys list --account-name asx-db-scraperdev --resource-group asx-db-rg

      - name: Test Function App Configuration
        run: |
          echo "Listing Function App settings..."
          az functionapp config appsettings list --name asx-db-scraper-dev --resource-group asx-db-rg --query "[].{name:name, value:value}" -o table

name: Test Azure Credentials

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show Azure CLI Version
        run: az version

      - name: Show Current Azure Context
        run: |
          echo "Current Azure Context:"
          az account show

      - name: List All Resource Groups
        run: |
          echo "Listing all resource groups:"
          az group list --query "[].{name:name, location:location}" -o table

      - name: Test Resource Group Access
        run: |
          echo "Testing access to resource group..."
          if ! az group show --name asx-db-rg; then
            echo "Failed to access resource group. Checking if it exists..."
            if ! az group exists --name asx-db-rg; then
              echo "Resource group does not exist. Creating it..."
              az group create --name asx-db-rg --location australiaeast
            else
              echo "Resource group exists but access failed. Check permissions."
              exit 1
            fi
          fi
          
          echo "Listing resources in the resource group..."
          az resource list --resource-group asx-db-rg --query "[].{name:name, type:type}" -o table

      - name: Test Function App Access
        run: |
          echo "Testing Function App access..."
          if ! az functionapp show --name asx-db-scraper-dev --resource-group asx-db-rg; then
            echo "Function app not found. Checking if it exists..."
            if ! az functionapp list --resource-group asx-db-rg --query "[?contains(name, 'asx-db-scraper')]" -o table; then
              echo "No function apps found in resource group."
            fi
          fi

      - name: Test Storage Account Access
        run: |
          echo "Testing Storage Account access..."
          if ! az storage account show --name asx-db-scraperdev --resource-group asx-db-rg; then
            echo "Storage account not found. Checking if it exists..."
            if ! az storage account list --resource-group asx-db-rg --query "[?contains(name, 'asx-db-scraper')]" -o table; then
              echo "No storage accounts found in resource group."
            fi
          fi

      - name: Test Cosmos DB Access
        run: |
          echo "Testing Cosmos DB access..."
          if ! az cosmosdb show --name asx-db-scraper-dev --resource-group asx-db-rg; then
            echo "Cosmos DB not found. Checking if it exists..."
            if ! az cosmosdb list --resource-group asx-db-rg --query "[?contains(name, 'asx-db-scraper')]" -o table; then
              echo "No Cosmos DB accounts found in resource group."
            fi
          fi

      - name: Test Key Vault Access
        run: |
          echo "Testing Key Vault access..."
          if ! az keyvault show --name asx-db-scraper-dev-kv --resource-group asx-db-rg; then
            echo "Key Vault not found. Checking if it exists..."
            if ! az keyvault list --resource-group asx-db-rg --query "[?contains(name, 'asx-db-scraper')]" -o table; then
              echo "No Key Vaults found in resource group."
            fi
          fi

      - name: Show Service Principal Permissions
        run: |
          echo "Checking service principal permissions..."
          SP_ID=$(az ad sp list --display-name "asx-db-scraper-sp" --query "[0].id" -o tsv)
          if [ -n "$SP_ID" ]; then
            echo "Service Principal ID: $SP_ID"
            az role assignment list --assignee $SP_ID --all --query "[].{role:roleDefinitionName, scope:scope}" -o table
          else
            echo "Service principal not found!"
          fi 