name: Test Azure Credentials

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test Resource Group Access
        run: |
          echo "Testing access to resource group..."
          az group show --name asx-db-scraper-rg
          
          echo "Listing resources in the resource group..."
          az resource list --resource-group asx-db-scraper-rg --query "[].{name:name, type:type}" -o table
          
          echo "Testing Cosmos DB access..."
          az cosmosdb show --name asx-db-scraper-dev --resource-group asx-db-scraper-rg
          
          echo "Testing Function App access..."
          az functionapp show --name asx-db-scraper-dev --resource-group asx-db-scraper-rg
          
          echo "Testing Key Vault access..."
          az keyvault show --name asx-db-scraper-dev-kv --resource-group asx-db-scraper-rg

      - name: Test Storage Account Access
        run: |
          echo "Testing Storage Account access..."
          az storage account show --name asx-db-scraperdev --resource-group asx-db-scraper-rg
          
          echo "Listing storage account keys..."
          az storage account keys list --account-name asx-db-scraperdev --resource-group asx-db-scraper-rg

      - name: Test Function App Configuration
        run: |
          echo "Listing Function App settings..."
          az functionapp config appsettings list --name asx-db-scraper-dev --resource-group asx-db-scraper-rg --query "[].{name:name, value:value}" -o table
