name: Test Azure Credentials

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test Azure CLI
        run: |
          echo "Testing Azure CLI access..."
          az account show
          
          echo "Testing resource group access..."
          az group show --name asx-db-rg

      - name: Test Resource Access
        run: |
          # Get parameters from dev environment file
          FUNCTION_APP_NAME=$(az deployment group show \
            --resource-group asx-db-rg \
            --name main \
            --query "properties.outputs.functionAppName.value" \
            -o tsv)
            
          echo "Testing Function App access..."
          az functionapp show \
            --resource-group asx-db-rg \
            --name $FUNCTION_APP_NAME

          echo "Testing Key Vault access..."
          KEY_VAULT_NAME=$(az deployment group show \
            --resource-group asx-db-rg \
            --name main \
            --query "properties.outputs.keyVaultName.value" \
            -o tsv)
          az keyvault show --name $KEY_VAULT_NAME

      - name: Test Storage Account Access
        run: |
          echo "Testing Storage Account access..."
          az storage account show --name asx-db-scraperdev --resource-group asx-db-rg
          
          echo "Listing storage account keys..."
          az storage account keys list --account-name asx-db-scraperdev --resource-group asx-db-rg

      - name: Test Function App Configuration
        run: |
          echo "Listing Function App settings..."
          az functionapp config appsettings list --name asx-db-scraper-dev --resource-group asx-db-rg --query "[].{name:name, value:value}" -o table
